version = "3.9"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./exports:/app/exports
      - ./models:/app/models
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start